### ISSUE TITLE
How name foot print for RFM9XW_XXXS2 ?

### ISSUE THREAD

**Issue by Misca1234** [KiCad/RF_Modules.pretty#24]
Hi

I am looking into to re push 
https://github.com/KiCad/kicad-library/pull/1104

But want both foot prints but unsecure of the foot print names,
Shall the SMD variant have SMDIP as prefix, like the DIP packages
Can we accept the THT variant when we don't have the exact distance from the edge to the pin holes ?
I measured on the paper to 1.6 mm

![bild](https://user-images.githubusercontent.com/25547797/30987214-804a29f6-a496-11e7-8077-ff321208899b.png)

![bild](https://user-images.githubusercontent.com/25547797/30987229-8efd9f78-a496-11e7-9ebd-f7033c153821.png)

**Comment by jkriege2** [comment]
Hi!
Naming should be in the `MANUFACTURER_DEVICE`-form, i.e. here I wuld suggest `Hoperf_RFM9xW_THT` and `Hoperf_RFM9x_SMD`

**Comment by Misca1234** [comment]
ok, was a little unceartain depending on the new style for the DIP packages
